version: "3.6"

services:
  nginx:
    image: nginx:1.19.10-alpine
    ports:
      - "8005:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - lillydoo

  php:
    image: lillydoo_php:0.0.1
    build:
      context: ./
      dockerfile: ./docker/php/php.dockerfile
    volumes:
      - ./:/var/www/html
    user: lillydoo
    networks:
      - lillydoo

  sqllite:
    image: lillydoo_sqllite:3.1.0
    build:
      context: ./
      dockerfile: ./docker/sqllite/sqllite.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
      - ./db/:/my/sqlite/path/ # Here is the change
    command: pipenv run gunicorn --bind=0.0.0.0:5000 --reload app:app
    networks:
      - lillydoo

  composer:
    image: lillydoo_composer:0.0.1
    build:
      context: ./
      dockerfile: ./docker/composer/composer.dockerfile
    volumes:
      - ./:/var/www/html
      - $HOME/.composer/cache:/home/lillydoo/.composer/cache
    working_dir: /var/www/html
    depends_on:
      - php
    user: lillydoo
    networks:
      - lillydoo

networks:
  lillydoo:

